### ISSUE TITLE
[dnd5e system] auto expanding damage tray doesn't scroll

### ISSUE THREAD

**Issue by roguedevjake** [etiquettestartshere/effectivetray#32]
When setting the damage tray to auto expand the chat doesn't scroll after expanding, leaving the apply button below where the "jump to bottom" button would be if it appeared.

**Comment by etiquettestartshere** [comment]
i assume this is for the damage tray only? this is due to the fact that the damage tray is empty when accessed on the appropriate render hook, and the module uses a delay to access it after it has been injected. trays not scrolling to the bottom is a system issue (opening a tray will not scroll the chat). the reason this does not occur with the effects tray is, presumably, because the module succeeds in creating the message in its opened state, rather than opening it after the necessary delay for the damage tray. still, i will investigate a simple `scrollBottom()` based solution.

**Comment by etiquettestartshere** [comment]
pushed a patch for this feature. it isn't perfect, especially when selecting a new number of tokens on the damage tray, but it's what we've got until the system changes its behavior. please let me know if there are any issues with it
