### ISSUE TITLE
[Feature Request] Add option to hide permanent item effects from effect tray

### ISSUE THREAD

**Issue by BlackBadger777** [etiquettestartshere/effectivetray#96]
Foundry version: v12, build 331
System: DnD5e 3.3.1

I have some magic items that have an active effect granted to the wearer, as well as temporary effects that are granted to a target, which may or may not be the actor owning the item. Right now, both the permanent as well as the temporary effects are shown in the effect tray and could, theoretically, be applied to other targets. 

I would love for there to be an option that hides these permanent effects from the effect tray. This could be handled by singling out any AE that has "Effect Suspended" Unchecked and "Apply Effect to Actor" checked. These effects are (in my game, at least) never meant to be transferred to anyone other than the owner of the item, and thus take up unnecessary space. Worse, when Effective Tray grants players access to the effect tray, they might accidentally apply the wrong effect(s). 

I don't know how feasible this is, but I figured it was worth a shot.

**Comment by etiquettestartshere** [comment]
in my unmerged current branch, effects with 'Apply Effect to Actor' are already filtered out. would this alone (and not filtering out 'Effect Suspended') cover all your cases, too?

originally, i was going to wait until the system made this change (it was on a 4.0 milestone), but since the branch with it has been deleted, its fate is uncertain, so i will probably go ahead and merge this soon
